---
title: "Planning search"
subtitle: "Metrics description for different planning solution searches"
author: "Ilya Semenov"
date: '6 October 2017'
output: pdf_document
---

#Tests summary

This report contains tests result and discussion for three different non-heuristic planning solutions and A-star search with three different heuristics for three cargo-transfer tasks defined in [project briefing](https://github.com/isemenov2015/AIND-Planning/blob/master/README.md).
Non-heuristic planning solutions tested:

* breadth-first search
* depth-first search
* uniform-cost search

A-star search solutions with following heuristics tested:

* h_1 pseudo-heuristic, that returns constant value of 1 for any planning graph node
* ignore preconditions heuristic
* planning graph level sum heuristic

All test runs finished successfully, exact solutions found, runtime required and some related info provided in relevant sections of this document. By the construction of the algorithm breadth-first search and uniform cost search produced optimal solutions in terms of operations length for the path. Depth-first search produced significantly longer non-optimal paths for all test cases. All A-star searches produced optimal solutions.

#Solutions comparison

##Optimal plans

Optimal plans lengths for for cargo problems 1, 2, 3 are as follows:

|Problem No|   Optimal path length |
|-----|--------|
|    1 |         6    |
|    2 |         9    |
|    3 |         12    |

Specific examples of optimal paths may be found in the *Non-heuristic solutions / Breadth-first search* section of this document.

##Non-heuristic solutions results discussion

Specific results are located in the *Non-heuristic solutions* section of this document.

Breadth-first search (BFS), depth-first search (DFS) and uniform-cost search (UCS) were chosen for non-heuristic solution comparison.

BFS and UCS both produce optimal paths by the construction of the algorithms but it comes with a price of the number of planning graph vertices visited. Since the graph edges length for UCS is a constant during the whole computation session UCS and BFS are almost the same in terms of solution construction. The only difference is that the vertices are added to the solution in a different order but based on a same criteria.
DFS produce fast and scarce in terms of visited nodes number solution but the paths produced are definitely far from optimal in terms of length.

##Heuristic solutions results discussion

#Non-heuristic solutions

##Breadth-first search

### Air Cargo Problem 1

|Expansions|   Goal Tests|   New Nodes|
|-----|--------|-------|
|    43 |         56    |     180 |

Plan length: 6  Time elapsed in seconds: 0.045186803331299104

Plan produced:

Load(C1, P1, SFO),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Unload(C2, P2, SFO),
Fly(P1, SFO, JFK),
Unload(C1, P1, JFK)

### Air Cargo problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|   3346 |        4612 |       30534 |

Plan length: 9  Time elapsed in seconds: 23.348714683500532

Plan produced:

Load(C1, P1, SFO),
Load(C2, P2, JFK),
Load(C3, P3, ATL),
Fly(P1, SFO, JFK),
Unload(C1, P1, JFK),
Fly(P2, JFK, SFO),
Unload(C2, P2, SFO),
Fly(P3, ATL, SFO),
Unload(C3, P3, SFO)

### Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|  14120 |       17673 |       124926 |

Plan length: 12  Time elapsed in seconds: 124.470103887963

Plan produced:

Load(C1, SFO, P1),
Load(C2, JFK, P2),
Fly(P1, SFO, ATL),
Load(C3, ATL, P1),
Fly(P2, JFK, ORD),
Load(C4, ORD, P2),
Fly(P1, ATL, JFK),
Unload(C1, JFK, P1),
Unload(C3, JFK, P1),
Fly(P2, ORD, SFO),
Unload(C2, SFO, P2),
Unload(C4, SFO, P2)

##Depth first search

###Air Cargo Problem 1

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    21 |          22 |          84 |

Plan length: 20  Time elapsed in seconds: 0.028018328618808784

Plan produced:

Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Load(C2, P1, JFK),
Fly(P1, JFK, SFO),
Fly(P2, SFO, JFK),
Unload(C2, P1, SFO),
Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Load(C2, P2, SFO),
Fly(P1, JFK, SFO),
Load(C1, P2, SFO),
Fly(P2, SFO, JFK),
Fly(P1, SFO, JFK),
Unload(C2, P2, JFK),
Unload(C1, P2, JFK),
Fly(P2, JFK, SFO),
Load(C2, P1, JFK),
Fly(P1, JFK, SFO),
Fly(P2, SFO, JFK),
Unload(C2, P1, SFO)

###Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    107 |          108 |          959 |

Plan length: 105  Time elapsed in seconds: 0.5501376462219696

Plan produced:

Fly(P3, ATL, JFK),
Fly(P2, JFK, ATL),
Fly(P3, JFK, SFO),
Fly(P2, ATL, SFO),
Fly(P1, SFO, ATL),
Fly(P3, SFO, ATL),
Fly(P1, ATL, JFK),
Fly(P3, ATL, JFK),
Load(C2, P3, JFK),
Fly(P3, JFK, ATL),
Fly(P1, JFK, ATL),
Fly(P3, ATL, SFO),
Fly(P1, ATL, SFO),
Fly(P2, SFO, ATL),
Fly(P3, SFO, ATL),
Fly(P2, ATL, JFK),
Unload(C2, P3, ATL),
Fly(P3, ATL, JFK),
Fly(P2, JFK, ATL),
Fly(P3, JFK, SFO),
Fly(P2, ATL, SFO),
Fly(P1, SFO, ATL),
Fly(P3, SFO, JFK),
Fly(P1, ATL, JFK),
Load(C1, P2, SFO),
Fly(P3, JFK, ATL),
Fly(P1, JFK, ATL),
Fly(P2, SFO, ATL),
Fly(P3, ATL, JFK),
Fly(P2, ATL, JFK),
Fly(P1, ATL, SFO),
Fly(P3, JFK, ATL),
Unload(C1, P2, JFK),
Fly(P3, ATL, SFO),
Fly(P2, JFK, ATL),
Fly(P1, SFO, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Fly(P3, SFO, ATL),
Fly(P2, SFO, ATL),
Fly(P3, ATL, JFK),
Fly(P2, ATL, JFK),
Load(C1, P3, JFK),
Fly(P3, JFK, ATL),
Fly(P2, JFK, ATL),
Fly(P3, ATL, SFO),
Fly(P1, JFK, ATL),
Fly(P2, ATL, JFK),
Load(C3, P1, ATL),
Fly(P1, ATL, JFK),
Fly(P2, JFK, ATL),
Fly(P1, JFK, SFO),
Fly(P2, ATL, SFO),
Fly(P3, SFO, ATL),
Fly(P1, SFO, ATL),
Fly(P3, ATL, JFK),
Fly(P1, ATL, JFK),
Unload(C3, P1, JFK),
Fly(P3, JFK, ATL),
Fly(P1, JFK, ATL),
Fly(P3, ATL, SFO),
Fly(P1, ATL, SFO),
Fly(P2, SFO, ATL),
Fly(P3, SFO, ATL),
Fly(P2, ATL, JFK),
Fly(P3, ATL, JFK),
Fly(P1, SFO, ATL),
Fly(P2, JFK, ATL),
Unload(C1, P3, JFK),
Fly(P1, ATL, JFK),
Fly(P2, ATL, JFK),
Fly(P3, JFK, ATL),
Fly(P1, JFK, ATL),
Fly(P3, ATL, SFO),
Fly(P1, ATL, SFO),
Fly(P2, JFK, ATL),
Fly(P3, SFO, ATL),
Fly(P2, ATL, SFO),
Fly(P3, ATL, JFK),
Load(C3, P3, JFK),
Fly(P3, JFK, ATL),
Fly(P2, SFO, ATL),
Fly(P3, ATL, SFO),
Fly(P2, ATL, JFK),
Fly(P1, SFO, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Unload(C3, P3, SFO),
Fly(P1, JFK, SFO),
Fly(P3, SFO, ATL),
Fly(P2, SFO, ATL),
Fly(P3, ATL, JFK),
Fly(P2, ATL, JFK),
Fly(P1, SFO, ATL),
Fly(P3, JFK, ATL),
Fly(P1, ATL, JFK),
Load(C2, P3, ATL),
Fly(P3, ATL, JFK),
Fly(P2, JFK, ATL),
Fly(P1, JFK, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, SFO),
Fly(P3, JFK, SFO),
Fly(P2, SFO, ATL),
Unload(C2, P3, SFO)

###Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|   292 |         293 |         2388 |

Plan length: 288  Time elapsed in seconds: 1.532692063256472

Plan produced:

Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Load(C2, P1, JFK),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Unload(C2, P1, SFO),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Load(C2, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Unload(C2, P2, ATL),
Fly(P2, ATL, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Load(C1, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Unload(C1, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Load(C1, P1, JFK),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Load(C3, P2, ATL),
Fly(P2, ATL, ORD),
Fly(P1, ATL, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, JFK),
Fly(P2, JFK, SFO),
Fly(P1, JFK, SFO),
Unload(C3, P2, SFO),
Fly(P2, SFO, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, JFK),
Fly(P1, ATL, JFK),
Unload(C1, P1, JFK),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, SFO),
Load(C3, P2, SFO),
Fly(P2, SFO, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Unload(C3, P2, JFK),
Fly(P1, ATL, JFK),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, SFO),
Load(C2, P2, ATL),
Fly(P2, ATL, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Unload(C2, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C3, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C3, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C3, P1, SFO),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Unload(C3, P1, ATL),
Fly(P1, ATL, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, SFO),
Fly(P2, ATL, JFK),
Load(C2, P1, SFO),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, JFK),
Fly(P2, ATL, SFO),
Unload(C2, P1, JFK),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Load(C4, P2, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, JFK),
Fly(P1, ATL, JFK),
Fly(P2, JFK, SFO),
Fly(P1, JFK, SFO),
Unload(C4, P2, SFO),
Fly(P2, SFO, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, JFK),
Fly(P1, ATL, JFK),
Unload(C2, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, SFO),
Load(C4, P2, SFO),
Fly(P2, SFO, ORD),
Fly(P1, SFO, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, ORD),
Fly(P2, ATL, JFK),
Unload(C4, P2, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, ORD),
Fly(P1, ATL, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, SFO),
Load(C3, P2, ATL),
Fly(P2, ATL, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Unload(C3, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C4, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C4, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C4, P1, SFO),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Unload(C4, P1, ATL),
Fly(P1, ATL, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, SFO),
Fly(P2, ATL, JFK),
Load(C3, P1, SFO),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C3, P1, JFK),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C3, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Load(C4, P2, ATL),
Fly(P2, ATL, ORD),
Fly(P1, ATL, ORD),
Fly(P2, ORD, SFO),
Fly(P1, ORD, SFO),
Fly(P2, SFO, JFK),
Fly(P1, SFO, JFK),
Unload(C3, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, SFO),
Fly(P1, ORD, ATL),
Unload(C4, P2, SFO),
Fly(P1, ATL, JFK),
Fly(P2, SFO, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, SFO),
Fly(P2, ATL, JFK),
Load(C4, P1, SFO),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, JFK),
Fly(P2, ATL, SFO),
Unload(C4, P1, JFK),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C2, P2, SFO),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C4, P2, JFK),
Fly(P2, JFK, ORD),
Fly(P1, SFO, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, ORD),
Fly(P2, ATL, SFO),
Fly(P1, ORD, ATL),
Unload(C4, P2, SFO)

##Uniform cost search

###Air Cargo Problem 1

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    55 |          57 |         224 |

Plan length: 6  Time elapsed in seconds: 0.09636143442600302

Plan produced:

Load(C1, P1, SFO),
Load(C2, P2, JFK),
Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Unload(C1, P1, JFK),
Unload(C2, P2, SFO)

###Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    4853 |          4855 |         44041 |

Plan length: 9  Time elapsed in seconds: 17.599227649561485

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Load(C3, P3, ATL),
Fly(P3, ATL, SFO),
Unload(C3, P3, SFO),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)

###Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    18233 |          18235 |         159697 |

Plan length: 12  Time elapsed in seconds:  70.27345966101211

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, ATL),
Load(C2, P2, JFK),
Fly(P2, JFK, ORD),
Load(C3, P1, ATL),
Load(C4, P2, ORD),
Fly(P2, ORD, SFO),
Unload(C4, P2, SFO),
Fly(P1, ATL, JFK),
Unload(C3, P1, JFK),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)

#Heuristic solutions

##A-star search with h_1 pseudo-heuristic

###Air Cargo Problem 1

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    55 |          57 |         224 |

Plan length: 6  Time elapsed in seconds: 0.054725722040685175

Plan produced:

Load(C1, P1, SFO),
Load(C2, P2, JFK),
Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Unload(C1, P1, JFK),
Unload(C2, P2, SFO)

###Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    4853 |          4855 |         44041 |

Plan length: 9  Time elapsed in seconds: 15.849154030346117

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Load(C3, P3, ATL),
Fly(P3, ATL, SFO),
Unload(C3, P3, SFO),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)

###Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    18233 |          18235 |         159697 |

Plan length: 12  Time elapsed in seconds: 71.06583018395725

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, ATL),
Load(C2, P2, JFK),
Fly(P2, JFK, ORD),
Load(C3, P1, ATL),
Load(C4, P2, ORD),
Fly(P2, ORD, SFO),
Unload(C4, P2, SFO),
Fly(P1, ATL, JFK),
Unload(C3, P1, JFK),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)

##A-star search with Ignore preconditions heuristic

###Air Cargo Problem 1

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    41 |          43 |         170 |

Plan length: 6  Time elapsed in seconds: 0.049065529391238163

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, JFK),
Unload(C1, P1, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Unload(C2, P2, SFO)

###Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    1428 |          1430 |         13085 |

Plan length: 9  Time elapsed in seconds: 5.579498884066904

Plan produced:

Load(C3, P3, ATL),
Fly(P3, ATL, SFO),
Unload(C3, P3, SFO),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Unload(C2, P2, SFO),
Load(C1, P1, SFO),
Fly(P1, SFO, JFK),
Unload(C1, P1, JFK)

###Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    4859 |          4861 |         43129 |

Plan length: 12  Time elapsed in seconds: 21.878993299664558

Plan produced:

Load(C2, P2, JFK),
Fly(P2, JFK, ORD),
Load(C4, P2, ORD),
Fly(P2, ORD, SFO),
Unload(C4, P2, SFO),
Load(C1, P1, SFO),
Fly(P1, SFO, ATL),
Load(C3, P1, ATL),
Fly(P1, ATL, JFK),
Unload(C3, P1, JFK),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)

##A-star search with planning graph level sum heuristic

###Air Cargo Problem 1

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    11 |          13 |         50 |

Plan length: 6  Time elapsed in seconds: 1.1715631668657478

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Unload(C1, P1, JFK),
Unload(C2, P2, SFO)

###Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    114 |          116 |         1120 |

Plan length: 9  Time elapsed in seconds: 321.423673255422

Plan produced:

Load(C1, P1, SFO),
Fly(P1, SFO, JFK),
Load(C2, P2, JFK),
Fly(P2, JFK, SFO),
Load(C3, P3, ATL),
Fly(P3, ATL, SFO),
Unload(C3, P3, SFO),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)

###Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    309 |          311 |         2851 |

Plan length: 12  Time elapsed in seconds: 1275.4574559883408

Plan produced:

Load(C2, P2, JFK),
Fly(P2, JFK, ORD),
Load(C4, P2, ORD),
Fly(P2, ORD, SFO),
Load(C1, P1, SFO),
Fly(P1, SFO, ATL),
Load(C3, P1, ATL),
Fly(P1, ATL, JFK),
Unload(C4, P2, SFO),
Unload(C3, P1, JFK),
Unload(C2, P2, SFO),
Unload(C1, P1, JFK)