---
title: "Planning search"
subtitle: "Metrics description for non-heuristic planning solution searches"
author: "Ilya Semenov"
date: '2 October 2017'
output: pdf_document
---

#Tests summary

In total three non-heuristics planning solutions were tested, each on three cargo transfer tasks defined in [project briefing](https://github.com/isemenov2015/AIND-Planning/blob/master/README.md).
Those solutions are: breadth-first search, depth-first-search and uniform cost search.
All test runs finished successfully, exact solutions found, runtime required and some related info provided in relevant sections of this document. By the construction of the algorithm breadth-first search and uniform cost search produced optimal solutions in terms of operations length for the path. Depth-first search produced significantly longer non-optimal paths for all test cases.

#Breadth-first search

## Air Cargo Problem 1

|Expansions|   Goal Tests|   New Nodes|
|-----|--------|-------|
|    43 |         56    |     180 |

Plan length: 6  Time elapsed in seconds: 0.045186803331299104

Plan produced:

Load(C1, SFO, P1),
Load(C2, JFK, P2),
Fly(P2, JFK, SFO),
Unload(C2, SFO, P2),
Fly(P1, SFO, JFK),
Unload(C1, JFK, P1)

## Air Cargo problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|   3346 |        4612 |       30534 |

Plan length: 9  Time elapsed in seconds: 17.151455844655164

Plan produced:

Load(C1, SFO, P1),
Load(C2, JFK, P2),
Load(C3, ATL, P3),
Fly(P1, SFO, JFK),
Unload(C1, JFK, P1),
Fly(P2, JFK, SFO),
Unload(C2, SFO, P2),
Fly(P3, ATL, SFO),
Unload(C3, SFO, P3)

## Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|  14120 |       17673 |       124926 |

Plan length: 12  Time elapsed in seconds: 172.5876692353786

Plan produced:

Load(C1, SFO, P1),
Load(C2, JFK, P2),
Fly(P1, SFO, ATL),
Load(C3, ATL, P1),
Fly(P2, JFK, ORD),
Load(C4, ORD, P2),
Fly(P1, ATL, JFK),
Unload(C1, JFK, P1),
Unload(C3, JFK, P1),
Fly(P2, ORD, SFO),
Unload(C2, SFO, P2),
Unload(C4, SFO, P2)

#Depth first search

##Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    21 |          22 |          84 |

Plan length: 20  Time elapsed in seconds: 0.028018328618808784

Plan produced:

Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Load(C2, JFK, P1),
Fly(P1, JFK, SFO),
Fly(P2, SFO, JFK),
Unload(C2, SFO, P1),
Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Load(C2, SFO, P2),
Fly(P1, JFK, SFO),
Load(C1, SFO, P2),
Fly(P2, SFO, JFK),
Fly(P1, SFO, JFK),
Unload(C2, JFK, P2),
Unload(C1, JFK, P2),
Fly(P2, JFK, SFO),
Load(C2, JFK, P1),
Fly(P1, JFK, SFO),
Fly(P2, SFO, JFK),
Unload(C2, SFO, P1)

##Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|   292 |         293 |         2388 |

Plan length: 288  Time elapsed in seconds: 1.532692063256472

Plan produced:

Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Load(C2, JFK, P1),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Unload(C2, SFO, P1),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Load(C2, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Unload(C2, ATL, P2),
Fly(P2, ATL, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Load(C1, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Unload(C1, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Load(C1, JFK, P1),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Load(C3, ATL, P2),
Fly(P2, ATL, ORD),
Fly(P1, ATL, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, JFK),
Fly(P2, JFK, SFO),
Fly(P1, JFK, SFO),
Unload(C3, SFO, P2),
Fly(P2, SFO, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, JFK),
Fly(P1, ATL, JFK),
Unload(C1, JFK, P1),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, SFO),
Load(C3, SFO, P2),
Fly(P2, SFO, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Unload(C3, JFK, P2),
Fly(P1, ATL, JFK),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, SFO),
Load(C2, ATL, P2),
Fly(P2, ATL, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Unload(C2, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C3, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C3, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C3, SFO, P1),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Unload(C3, ATL, P1),
Fly(P1, ATL, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, SFO),
Fly(P2, ATL, JFK),
Load(C2, SFO, P1),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, JFK),
Fly(P2, ATL, SFO),
Unload(C2, JFK, P1),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C2, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Load(C4, ORD, P2),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, JFK),
Fly(P1, ATL, JFK),
Fly(P2, JFK, SFO),
Fly(P1, JFK, SFO),
Unload(C4, SFO, P2),
Fly(P2, SFO, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, JFK),
Fly(P1, ATL, JFK),
Unload(C2, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, SFO),
Load(C4, SFO, P2),
Fly(P2, SFO, ORD),
Fly(P1, SFO, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, ORD),
Fly(P2, ATL, JFK),
Unload(C4, JFK, P2),
Fly(P1, ORD, ATL),
Fly(P2, JFK, ORD),
Fly(P1, ATL, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, SFO),
Load(C3, ATL, P2),
Fly(P2, ATL, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, JFK),
Fly(P1, ORD, ATL),
Fly(P2, JFK, SFO),
Fly(P1, ATL, JFK),
Unload(C3, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C4, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C4, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C4, SFO, P1),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Unload(C4, ATL, P1),
Fly(P1, ATL, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, SFO),
Fly(P2, ATL, JFK),
Load(C3, SFO, P1),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C3, JFK, P1),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C3, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Load(C4, ATL, P2),
Fly(P2, ATL, ORD),
Fly(P1, ATL, ORD),
Fly(P2, ORD, SFO),
Fly(P1, ORD, SFO),
Fly(P2, SFO, JFK),
Fly(P1, SFO, JFK),
Unload(C3, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, SFO),
Fly(P1, ORD, ATL),
Unload(C4, SFO, P2),
Fly(P1, ATL, JFK),
Fly(P2, SFO, ORD),
Fly(P1, JFK, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, SFO),
Fly(P2, ATL, JFK),
Load(C4, SFO, P1),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, JFK),
Fly(P2, ATL, SFO),
Unload(C4, JFK, P1),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C2, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, ORD),
Fly(P2, ORD, ATL),
Fly(P1, ORD, ATL),
Fly(P2, ATL, SFO),
Fly(P1, ATL, JFK),
Unload(C2, SFO, P2),
Fly(P1, JFK, ORD),
Fly(P2, SFO, ORD),
Fly(P1, ORD, ATL),
Fly(P2, ORD, ATL),
Fly(P1, ATL, SFO),
Fly(P2, ATL, JFK),
Load(C4, JFK, P2),
Fly(P2, JFK, ORD),
Fly(P1, SFO, JFK),
Fly(P2, ORD, ATL),
Fly(P1, JFK, ORD),
Fly(P2, ATL, SFO),
Fly(P1, ORD, ATL),
Unload(C4, SFO, P2)

#Uniform cost search

##Air Cargo Problem 1

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    55 |          57 |         224 |

Plan length: 6  Time elapsed in seconds: 0.09636143442600302

Plan produced:

Load(C1, SFO, P1),
Load(C2, JFK, P2),
Fly(P1, SFO, JFK),
Fly(P2, JFK, SFO),
Unload(C1, JFK, P1),
Unload(C2, SFO, P2)

##Air Cargo Problem 2

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    4853 |          4855 |         44041 |

Plan length: 9  Time elapsed in seconds: 22.710844643323785
Load(C1, SFO, P1),
Fly(P1, SFO, JFK),
Load(C2, JFK, P2),
Fly(P2, JFK, SFO),
Load(C3, ATL, P3),
Fly(P3, ATL, SFO),
Unload(C3, SFO, P3),
Unload(C2, SFO, P2),
Unload(C1, JFK, P1)

##Air Cargo Problem 3

|Expansions |   Goal Tests |   New Nodes |
|-----|--------|-------|
|    18233 |          18235 |         159697 |

Plan length: 12  Time elapsed in seconds: 109.60073753427338
Load(C1, SFO, P1),
Fly(P1, SFO, ATL),
Load(C2, JFK, P2),
Fly(P2, JFK, ORD),
Load(C3, ATL, P1),
Load(C4, ORD, P2),
Fly(P2, ORD, SFO),
Unload(C4, SFO, P2),
Fly(P1, ATL, JFK),
Unload(C3, JFK, P1),
Unload(C2, SFO, P2),
Unload(C1, JFK, P1)